version: '3.4'
services:
  iqfeed:
    image: xhkm/iqfeed
    container_name: iqfeed
    ports:
     - "5009:5009"
     - "9100:9100"
     - "9200:9200"
     - "9300:9300"
     - "9400:9400"
     - "8088:8080"
     - "5901:5900"
    environment:
      IQFEED_PRODUCT_ID: "MATLAB_1694"
      IQFEED_LOGIN: "489834"
      IQFEED_PASSWORD: "35448408"
    volumes:
      - /var/log/iqfeed:/root/DTN/IQFeed
      - /var/log/distdnnd:/var/log/distdnnd
    healthcheck:
      test: ["CMD", "python3", "/root/is_iqfeed_running.py"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 1m

  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    restart: always
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: autoheal      
